### ISSUE TITLE
FIX - API - auth

### ISSUE THREAD

**Issue by LynchHarrison** [chingu-voyages/v46-tier3-team-37#77]
Currently the use of auth is creating a new connection to the prisma database every time any auth data is being grabbed.

This is where importing prisma from @lib/prisma (reusing the same connection) is needed

![Image](https://github.com/chingu-voyages/v46-tier3-team-37/assets/31375925/95f4dd76-751e-4c40-8686-f3f565d3c2ea)

**Comment by SeanPaulson** [comment]
If we get a chance to set up connection pooling that would help resolve that issue.
I can look into what options are available and see if I can set it up. 

Also a reverse proxy server with load balancing and better security lol 😅.... but definitely a pooling manager.
